internalName: urj

locales:
  en:
    name: &bundleName "FUPA keyboards"
    description: "Keyboards for FUPA from the Divvun group at UiT."
  nb:
    name: "FUPA-tastatur"
    description: "Tastatur for FUPA fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [urj_FI-mobile, urj_FI-mac, urj_FI-win]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.urj
    icon: images/urj-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.urj
    bundleName: *bundleName
    icon: images/urj-icon.png

  osx:
    <<: *AppleID
    icon: images/urj-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "replace-with-real-uuid-one-for-each-language"
