locales:
  en:
    name: FUPA keyboards
    description: Keyboards for FUPA from the Divvun group at UiT.
  nb:
    name: FUPA-tastatur
    description: Tastatur for FUPA fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
